name: 'Action Setup'

on:
  workflow_dispatch:

jobs:
  action-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Show setup
        run: |
          cat /etc/*release*
          echo ---
          docker version
          echo ---
          sudo ls /etc/apt/sources.list.d
          sudo cat /etc/apt/sources.list.d/docker.list
          echo --
          dpkg -L docker-ce-cli
          echo --
          dpkg -L docker-ce
